### ISSUE TITLE
Building and running docker images

### ISSUE THREAD

**Issue by domenkozar** [domenkozar/nix.dev#11]
Example from https://fridh.github.io/nix-tutorials/tutorials/03-images/01-creating-a-docker-image.html

**Comment by edibopp** [comment]
I have done this already for the NixOS homepage (https://github.com/NixOS/nixos-homepage/pull/418), so I can migrate that content here. (And perhaps make it a bit more standalone, than using a full Python web service.)

**Comment by domenkozar** [comment]
Yeah, it would be best to have something simple as an example in link above.

**Comment by domenkozar** [comment]
Done in #58
