### ISSUE TITLE
fully reproducible example not reproducible

### ISSUE THREAD

**Issue by davidak** [domenkozar/nix.dev#44]
>The following is a fully reproducible example https://github.com/domenkozar/nix.dev/blob/96302feb9bac102d6eb207a4f468efcaabed8fb1/source/tutorials/ad-hoc-developer-environments.rst#towards-reproducibility

No

>git version 2.25.0

git version 2.25.4

**Comment by domenkozar** [comment]
Thanks, fixed in https://github.com/domenkozar/nix.dev/commit/03f8d1b07a5f5a435abc5c92326fc0636e8557e6
