### ISSUE TITLE
Use of anti-patterns in the tutorials

### ISSUE THREAD

**Issue by DamienCassou** [domenkozar/nix.dev#61]
The tutorials contain occurences of the anti-patterns. For example, [Pinning Nixpkgs](https://nix.dev/reference/pinning-nixpkgs.html) contains:

```
with import (fetchTarball https://github.com/NixOS/nixpkgs/archive/nixos-20.03.tar.gz) {};

stdenv.mkDerivation { … }
```

which groups 2 anti-patterns:
- [Unquoted URLs](https://nix.dev/anti-patterns/language.html#unquoted-urls)
- [with attrset; ... expression](https://nix.dev/anti-patterns/language.html#with-attrset-expression)

Would you like a PR fixing those?

**Comment by domenkozar** [comment]
Please!

**Comment by domenkozar** [comment]
https://github.com/domenkozar/nix.dev/commit/4d89d507ec94203d70e25f521c5bbff97997fe22
